app: htv
org: taftouch
service: htv-api-v1
provider:
  name: aws
  runtime: python3.8
  region: eu-west-1

package:
  exclude:
    - save/**
    - test/**
    - test.py
    - train.py

functions:
  classify:
    handler: handler.classification
    memorySize: 2048
    timeout: 16
    events: 
      - httpApi:
          method: GET
          path: /v1/img/classify-3

custom:
  s3Sync:
    - bucketName: htv-api-v1-model-${opt:stage} 
      localDir: /save

plugins:
  - serverless-s3-sync

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: htv-api-v1-model-${opt:stage} 
