app: htv
org: taftouch
service: htv-api-v1

provider:
  name: aws
  stage: prod
  runtime: python3.8
  region: eu-west-1

  apiKeys:
    - devApiKey
    - htvApiKey
  usagePlan:
    quota:
      limit: 100000
      offset: 1
      period: MONTH

package:
  exclude:
    - save/**
    - test/**
    - test.py
    - train.py

functions:
  classify:
    handler: handler.classification
    memorySize: 3008
    timeout: 16
    events: 
      - http:
          method: GET
          path: /img/classify-3

custom:
  vars:
    s3-model: htv-api-models
  s3Sync:
    - bucketName: ${self:custom.vars.s3-model}
      localDir: /save
      bucketPrefix: /v1/c3

plugins:
  - serverless-s3-sync

resources:
  Resources:
    ModelBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.vars.s3-model}
