app: htv
org: taftouch
service: htv-api-v1

provider:
  name: aws
  stage: prod
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    S3_MODELS: ${self:custom.vars.s3-model}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:ListBucket"
         - "s3:GetBucketLocation"
       Resource: arn:aws:s3:::${self:custom.vars.s3-model}
    -  Effect: "Allow"
       Action:
         - "s3:GetObject"
         - "s3:GetObjectAcl"
       Resource: arn:aws:s3:::${self:custom.vars.s3-model}/*

package:
  exclude:
    - save/**
    - test.py
    - train.py

functions:
  k1006:
    handler: handler.k1006
    memorySize: 1024
    timeout: 16
    events:
      - httpApi:
          method: POST
          path: /img/k1006
          cors: true

custom:
  vars:
    s3-model: htv-api-models
  s3Sync:
    - bucketName: ${self:custom.vars.s3-model}
      localDir: save
      bucketPrefix: v1

plugins:
  - serverless-s3-sync

resources:
  Resources:
    HTVModelBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.vars.s3-model}
