app: htv
org: taftouch
service: htv-api-v1

provider:
  name: aws
  stage: prod
  runtime: nodejs12.x
  region: eu-west-1
  logs:
    httpApi: true

package:
  exclude:
    - save/**
    - test.py
    - train.py

functions:
  k1006:
    handler: handler.k1006
    memorySize: 1024
    timeout: 16
    events:
      - httpApi:
          method: POST
          path: /img/k1006
          cors: true

custom:
  vars:
    s3-model: htv-api-models
  s3Sync:
    - bucketName: ${self:custom.vars.s3-model}
      localDir: /save
      bucketPrefix: /v1/k1006

plugins:
  - serverless-s3-sync

resources:
  Resources:
    ModelBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.vars.s3-model}
