app: htv
org: taftouch
service: htv-api-v1

provider:
  name: aws
  stage: prod
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    S3_MODELS: ${self:custom.vars.s3-model}
    S3_MODELS_URL: https://${self:custom.vars.s3-model}.s3-eu-west-1.amazonaws.com/v1/k1006/model.json
  apiKeys:
    - name: htvAccessKey
      value: EsmovigKaqMUUvBw475QzvVU95MdvdrW
    - name: devAccessKey
      value: dstQtrU8tuNi0OeLJSyzKiNPcKUemxeA

package:
  exclude:
    - save/**
    - test.py
    - train.py

functions:
  k1006:
    handler: handler.k1006
    memorySize: 2048
    timeout: 24
    events:
      - http:
          method: POST
          path: /img/k1006
          private: true
          cors:
            origins: https://*.flessner.io
            allowCredentials: true

custom:
  vars:
    s3-model: htv-api-models
  s3Sync:
    - bucketName: ${self:custom.vars.s3-model}
      localDir: save
      bucketPrefix: v1

plugins:
  - serverless-s3-sync

resources:
  Resources:
    HTVModelBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.vars.s3-model}
        AccessControl: PublicRead
    HTVModelBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: 
          Ref: HTVModelBucket
        PolicyDocument:
          Statement: 
            - Sid: PublicRead
              Effect: Allow
              Principal: "*"
              Action: 
                - s3:GetObject
                - s3:GetObjectAcl
              Resource: arn:aws:s3:::${self:custom.vars.s3-model}/*
