app: htv
service: htv-api-v1
provider:
  name: aws
  runtime: python3.8

package:
  exclude:
    - save/**
    - test/**
    - test.py
    - train.py

functions:
  hello:
    handler: handler.classification
    event: 
      - httpApi:
          method: GET
          path: /v1/img/classify-3
